name: example
description: Example
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.13.6'

dependencies:
  flutter: { sdk: flutter }
  flutter_code_editor: { path: ../ }
  flutter_highlight:
    path: ../packages/highlight_with_jinja/flutter_highlight
  highlight: 
    path: ../packages/highlight_with_jinja/highlight
  http: ^1.1.0

dev_dependencies:
  flutter_test: { sdk: flutter }
  total_lints: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/settings/autoRefactoringSettings.json
