name: example
description: Example
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.13.6"

dependencies:
  flutter: { sdk: flutter }
  flutter_code_editor: { path: ../ }
  flutter_widget_from_html_core: ^0.17.0
  flutter_highlight:
     git:
      url: https://git.jinja.app/jinja.app/jinja_flutter_highlight.git
      ref: dev
  highlight:
    git:
      url: https://git.jinja.app/jinja.app/jinja_highlight.git
      ref: dev
  http: ^1.1.0
  jinja:
    # path: ../../forked_projects/jinja.dart
    git:
      url: https://github.com/AvoMandjian/jinja.dart.git
      ref: DP_5

dev_dependencies:
  flutter_test: { sdk: flutter }
  total_lints: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/settings/autoRefactoringSettings.json
